# Site
name: "数星"
description: "计算机 编程 数据科学 算法 computer-science programming data-science algorithms"
logo: assets/images/index.png
favicon: 'assets/images/favicon.ico'
baseurl: # ''
disqus: "randomforest"
email: 'kuangyl0212@gmail.com'
mailchimp-list: #'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
# SEO Related
google_site_verification : "t9SzaE_xkos5uNuvNX1e2-NKDD1Xn1JFiBJXSdu0lYE"
bing_site_verification   : "50958C20FA27280C7775CD4B4E39A7AA"

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    forest:
      name:           莫怀远
      en_name:        forest
      site:           https://kuangyl0212.github.io
      avatar:         #/assets/images/avatar1.jpg
      bio:            "万物皆备于我，反身而诚，乐莫大焉！"
      email:          kuangyl0212@gmail.com
      twitter:        #https://twitter.com/wowthemesnet


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: forest
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]